### ISSUE TITLE
Cannt execute anything after pulling an image

### ISSUE THREAD

**Issue by mrteera** [djmaze/armhf-ubuntu-docker#5]
My system information:
```
Docker version 17.09.0-ce, build afdb6d4
```
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
```
Linux gpu1 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I have tried both pull an image (mazzolino/armhf-ubuntu:14.04) or build it myself. I have got the same error:

```
standard_init_linux.go:185: exec user process caused "exec format error"
```

Or I have misunderstand that this docker can only be use for ARM device?

**Comment by djmaze** [comment]
@mrteera You have to [enable emulation support](https://github.com/djmaze/armhf-ubuntu-docker#emulation-support) on your machine in order to use this.

Sorry for the late answer.

**Comment by mrteera** [comment]
Thank you :)
